version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    volumes:
      - ./containers/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
        
  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.0
    expose:
        - "5044"
    command: --debug -f /etc/logstash/conf.d/
    volumes:
      - ./containers/logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Duser.timezone=Europe/Rome "
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    volumes:
      - ./containers/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    environment:
      LS_JAVA_OPTS: "-Duser.timezone=Europe/Rome "
    depends_on:
      - elasticsearch
      
volumes:
    esdata1:
      driver: local

